In [31]:
import torch 
x = torch.empty(5,3)
print(x)


tensor([[ 0.0000e+00, -2.0000e+00,  1.2431e-23],
        [ 2.8586e-42,  1.1210e-44,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00]])


In [32]:
x = torch.rand(5,3)
print(x)

tensor([[0.8676, 0.4224, 0.6706],
        [0.3162, 0.8762, 0.0353],
        [0.6994, 0.1390, 0.8991],
        [0.8687, 0.8698, 0.0813],
        [0.7163, 0.1328, 0.7203]])


In [33]:
x = torch.zeros(5,3,dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [34]:
x = torch.tensor([5.5,3])
print(x)

tensor([5.5000, 3.0000])


In [35]:
x = x.new_ones(5, 3, dtype=torch.double)      # new_* methods take in sizes
print(x)

x = torch.randn_like(x, dtype=torch.float)    # override dtype!
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[ 1.1034,  0.0317,  0.4706],
        [-1.2771, -0.3542, -0.2352],
        [ 0.8463,  0.9557,  0.4604],
        [-0.0776, -1.2049,  1.4936],
        [ 0.1810,  0.6276,  0.3158]])


In [36]:
print(x.size())

torch.Size([5, 3])


In [37]:
X = torch.rand(5,3)
Y = torch.rand(5,3)
print(X+Y)
print(torch.add(X, Y))
Z = torch.empty(5,3)
torch.add(X,Y,out=Z)
print(Z)

Y.add_(X)
print(Y)

tensor([[1.0332, 1.3762, 0.2857],
        [1.2958, 1.2079, 1.3214],
        [1.3985, 1.1763, 1.2872],
        [1.5419, 1.4081, 1.5142],
        [1.0587, 0.3233, 1.1608]])
tensor([[1.0332, 1.3762, 0.2857],
        [1.2958, 1.2079, 1.3214],
        [1.3985, 1.1763, 1.2872],
        [1.5419, 1.4081, 1.5142],
        [1.0587, 0.3233, 1.1608]])
tensor([[1.0332, 1.3762, 0.2857],
        [1.2958, 1.2079, 1.3214],
        [1.3985, 1.1763, 1.2872],
        [1.5419, 1.4081, 1.5142],
        [1.0587, 0.3233, 1.1608]])
tensor([[1.0332, 1.3762, 0.2857],
        [1.2958, 1.2079, 1.3214],
        [1.3985, 1.1763, 1.2872],
        [1.5419, 1.4081, 1.5142],
        [1.0587, 0.3233, 1.1608]])


In [38]:
X = torch.randn(4,4)
Y = X.view(16)
Z = X.view(-1,8)
print(X.size(),Y.size(),Z.size())
print(X)

print(Y)

print(Z)

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])
tensor([[-0.3425,  0.0798,  0.0445,  0.8660],
        [-0.3999, -0.6653, -0.2404,  0.1605],
        [ 0.8326,  0.2071,  2.3561, -0.0270],
        [-1.0154,  0.9580, -1.2988,  0.4136]])
tensor([-0.3425,  0.0798,  0.0445,  0.8660, -0.3999, -0.6653, -0.2404,  0.1605,
         0.8326,  0.2071,  2.3561, -0.0270, -1.0154,  0.9580, -1.2988,  0.4136])
tensor([[-0.3425,  0.0798,  0.0445,  0.8660, -0.3999, -0.6653, -0.2404,  0.1605],
        [ 0.8326,  0.2071,  2.3561, -0.0270, -1.0154,  0.9580, -1.2988,  0.4136]])


In [39]:
x = torch.randn(1)
print(x)
print(x.item())


tensor([-0.8269])
-0.8268657922744751


In [42]:
a = torch.ones(5)
print(a)


b = a.numpy()
print(b)


a.add_(1)
print(a)
print(b)



tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]
tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [43]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a,1,out=a)
print(a)
print(b)


[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
